### ISSUE TITLE
Update the browser compatibility list

### ISSUE THREAD

**Issue by Diachk** [Linkurious/documentation#103]
Safari is not supported anymore, let's make it official, also verify that we are still compatible the the versions mentioned here. 
![Screenshot 2019-09-23 at 14 59 31](https://user-images.githubusercontent.com/7275039/65431585-ffe11300-de19-11e9-9284-ee59a923e5e5.png)

**Comment by davidrapin** [comment]
@Diachk this has been discussed with frontend recently, please check with @aabarata

**Comment by Diachk** [comment]
related to https://github.com/Linkurious/linkurious-frontend/issues/2517

**Comment by fantandrea** [comment]
Could make sense:
* to put in the documentation list of `tested` or `validated` browsers where we specify the minimal version used to perform our tests
* mention the few external library that we used to say that as well as their browser is compatible with that they have high chances to get the system working. But it is clearly implicit that we didn't perform any test on it

I guess that our system will work fine also with other browsers or versions that we are not mentioning. E.g. some library put more restrictive version requirements due some feature that we actually are not using.

**Comment by thibaultlink** [comment]
@Diachk what's the status on this ? Do you need anything to close this issue ?

**Comment by thibaultlink** [comment]
Moved to 2.9 because the following related issue is also part of 2.9
https://github.com/Linkurious/linkurious-frontend/issues/2517

**Comment by fantandrea** [comment]
As per last David's comment in the closed front end issue:

> My proposal is about having two list:
> - the "officially supported" list: `(Firefox >= 50, Chrome >= 50, IE >= 11, Edge >= 12)`
> - the "fingers crossed" list: `iOS >= 7, Opera >= 50`
>
> For the "fingers crossed" list, we do not validate the product, we just install the polyfills and hope for the best. Some pages will work, some pages wont, and that's OK.

**Comment by thibaultlink** [comment]
@davidrapin should I update the doc with : 

```End-users will access Linkurious through a Web browser. All modern browsers are supported:

Firefox 50+
Chrome 50+
IE 11
Edge 12+
```

**Comment by davidrapin** [comment]
updated and pushed, ready for validation at https://dev.linkurio.us/doc-next/admin-manual/latest/requirements/#web-browser

**Comment by thibaultlink** [comment]
Good for me. Closing the issue.
