### ISSUE TITLE
Enhance Getting support instructions

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#107]
In the documentation exists a section on how to [get support](https://doc.linkurio.us/admin-manual/latest/support/) but the assumption is that the system is up and running to generate the automatic report.

This assumption is not alway valid especially in the case of an issue.

I suggest to add the instructions for manually compress the needed files or even better make the same feature available also from CLI.

**Comment by fantandrea** [comment]
@davidrapin wdyt?

**Comment by davidrapin** [comment]
good idea, +1

**Comment by fantandrea** [comment]
Validated.
