### ISSUE TITLE
Search Index cross reference

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#108]
Different pages in the Admin doc refers the index server but the data are outdate:

https://doc.linkurio.us/admin-manual/2.8.1/search/#using-the-configuration-file
1. Neo4j-to-ElasticSearch is linked to Neo4j Search
2. Neo4j Search is missing
3. CosmosDB is missing

https://doc.linkurio.us/admin-manual/2.8.1/search/#search-scalability-and-alternatives-to-elasticsearch
1. The link for `using the neo4j-to-elasticsearch Neo4j plugin` is broken

**Comment by davidrapin** [comment]
lots of outdated things indeed

**Comment by davidrapin** [comment]
most of that could be replaced with a link to this page: https://doc.linkurio.us/admin-manual/2.8.1/search-options/

**Comment by thibaultlink** [comment]
Reviewed and validated. Closing.
