### ISSUE TITLE
Update Download page with new Download Center

### ISSUE THREAD

**Issue by sheymann** [Linkurious/documentation#109]
On https://doc.linkurio.us/admin-manual/latest/download/

- Replace "https://linkurio.us/my-account/" with "https://get.linkurio.us/"
- Add a tutorial with screenshots on how to download LKE through the new Download Center

I'm available for help. :)

**Comment by fantandrea** [comment]
Validated.

**Comment by fantandrea** [comment]
@sheymann maybe you want to review the final result. It is on `preprod`branch, when solved the issues with the CI will be also online on the dev portal

**Comment by fantandrea** [comment]
@sheymann actually you can already see the same changes on the [doc for 2.8.2](https://dev.linkurio.us/doc/admin-manual/latest/download/)

**Comment by sheymann** [comment]
@fantandrea thanks, can you use the ACME customer instead of TEST for the screenshot? No need to blur the emails.

**Comment by fantandrea** [comment]
@sheymann are you ok with this?

![Screen Shot 2019-11-29 at 15 59 11](https://user-images.githubusercontent.com/12516532/69877025-5d358c80-12c1-11ea-8ffd-c8e1135fe3ed.png)

**Comment by sheymann** [comment]
Yes

**Comment by fantandrea** [comment]
@sheymann change merged in all preprod environments
