### ISSUE TITLE
Outdated version of crunchbase link

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#124]
In the user manual, in the [First Visualization section](https://doc.linkurio.us/user-manual/latest/visualization/) there is a link to download the Crunchbase data set, however this is done in a Neo4j v2.2.x version and new version 3.5.x failed to start it.
A multi step upgrade 2.2.x -> 2.3.12 -> 3.5.12 is needed.

Attached the migrated db [crunchbase-sfbay-neo4j v3.5.12.db.zip](https://github.com/Linkurious/documentation/files/4060349/crunchbase-sfbay-neo4j.v3.5.12.db.zip)

Also the counter seems to be different (at lease those the new values after the migration):
Nodes: 14 863
Edges: 47 090

**Comment by davidrapin** [comment]
notes:
- add  the new updated file to the doc repo (target: `documentation/content/shared/assets`) 
- change the link in the doc

**Comment by fantandrea** [comment]
@davidrapin how can I properly link the file in the shared folder? I alway received error saying `Broken internal link`.

I receive the error even when trying to put in the same folder `[download and install the dataset](/visualization/crunchbase-sfbay-neo4j.v3.5.12.db.zip)`

**Comment by davidrapin** [comment]
You are right, this does not work.
I created a repo for doc resources:
https://github.com/Linkurious/documentation-resources
