### ISSUE TITLE
Missing properties in Alert configuration

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#125]
In the [Alerts Configuration](https://doc.linkurio.us/admin-manual/2.8.2/config-alerts/) section of the admin doc `maxMatchTTL` and `enabled` parameters are not described. The latest one in particular should be refereed in the instructions to activate a Fault Tolerance environment.

**Comment by davidrapin** [comment]
I think `maxMatchTTL` was removed, @fantandrea where did you read about it?
 @francescoinfante can you confirm?

**Comment by fantandrea** [comment]
@davidrapin it was in my `production.json` file after a fresh installation.

And I can confirm it's still in the configuration parser

```javascript
  alerts: {
    properties: {
      enabled: {type: 'boolean'},
      maxMatchTTL: {check: ['integer', 0]},
      maxMatchesLimit: {check: ['integer', 1]},
      maxRuntimeLimit: {check: ['integer', 1]},
      maxConcurrency: {check: ['integer', 1]}
    }
  },
```

**Comment by davidrapin** [comment]
it's tolerated but unused since several versions if I remember correctly.

**Comment by fantandrea** [comment]
Ok, as soon as francesco confirm, I'll remove it from the scope.

Are you ok to document the `enable` parameter and specify that this is the correct way to disable alerts in a Fault Tolerance config?

**Comment by davidrapin** [comment]
@fantandrea regarding `enabled` and  fault tolerance: yes

**Comment by francescoinfante** [comment]
@davidrapin @fantandrea code has never been removed. Setting a matchTTL of 30 has a different meaning of setting a matchTTL of 0.

TTL = 30 means a match will disappear, if not confirmed, after 30 days
TTL = 0 means a match will disappear, if not confirmed, if it's not matched again at the following re-run of the alert.

I'm waiting for the case management epic to actually remove it and refactor alerts.

**Comment by fantandrea** [comment]
Content reviewed by @francescoinfante
