### ISSUE TITLE
Architecture schema not aligned to current supported technologies

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#126]
In the [admin doc of version 2.8](https://doc.linkurio.us/admin-manual/2.8.2/), the architectural schema shows outdated info:
- [x] Remove AllegroGraph
- [x] Remove DataStax
- [x] Remove Stardog
- [x] Add Azure Search
- [x] Add Neo4j Search
- [x] Add JanusSearch
- [x] Add OpenID Connect

**Comment by fantandrea** [comment]
@davidrapin do we have the original source file of the architecture (maybe in a slide or other editable formats)? It will be easier to change the blocks

**Comment by davidrapin** [comment]
There it is: https://github.com/Linkurious/documentation/blob/preprod-stable/content/admin/arch_schema.svg
I don't have any SVG editor at hand, maybe @PierreUI or @maxime-allex can help us with that?
