### ISSUE TITLE
Filter nodes - error on date format 

### ISSUE THREAD

**Issue by tbolke** [Linkurious/documentation#128]
@meaningfool 
The last section of the page https://doc.linkurio.us/user-manual/2.7.6/filter-node/ for v 2.7, explains that in order to filter a node by date, the date must be in a YYYY-MM-DD format

The right format is timestamp.

You agree?

**Comment by davidrapin** [comment]
Indeed, in 2.7, date must be stored as https://en.wikipedia.org/wiki/Unix_time timestamps to be filterable.
@maxime-allex can you confirm if the timestamp should be in seconds or in milliseconds?

**Comment by maxime-allex** [comment]
The timestamp should be in seconds.

**Comment by thibaultlink** [comment]
@meaningfool Since we have the necessary tech specs, I'm setting this as ready-to-dev.

**Comment by thibaultlink** [comment]
Date format changed to "Unix Timestamp (in seconds)". Closing this issue.
