### ISSUE TITLE
[Advanced Search Syntax] User documentation

### ISSUE THREAD

**Issue by thibaultlink** [Linkurious/documentation#130]
@thibaultlink commented on [Mon Feb 10 2020](https://github.com/Linkurious/linkurious-frontend/issues/2900)

Goal : Write user documentation for Advanced Search Syntax

Related Kickstart issues : 
Search Semantics (general specifications) : https://github.com/Linkurious/kickstart/issues/121
Clarify Advanced search property-filter contract : https://github.com/Linkurious/kickstart/issues/145
LKE search query language : https://github.com/Linkurious/kickstart/issues/164

**Comment by meaningfool** [comment]
Here are the instructions regarding the doc structure:

Authentication (not clickable or empty index.md) (NEW)
	Authentication in Linkurious Enterprise (authentication-in-linkurious-enterprise)(NEW)
	LDAP / Active Directory
	SSO with Azure AD
	SSO with Google
	SSO with OpenID Connect
	SSO with SAML2 / ADFS

Access control (not clickable or access/index.md empty)
	REMOVE enable-auth.md
	REMOVE users.md
	Managing users (managing-users)(NEW)
	Managing groups (managing-groups)(NEW)
	Standard access rights (standard-access-rights)(NEW)
	Property-key access rights (property-key-access rights)(NEW)
	Access control configuration options (access-control-configuration-options) (NEW)

Guest mode (not clickable or empty) (NEW)
	Guest mode (guest-mode) (CHANGED DIRECTORY)

And here are the zip for each new page:
[authentication-in-linkurious-enterprise.zip](https://github.com/Linkurious/documentation/files/4205627/authentication-in-linkurious-enterprise.zip)
[managing-users.zip](https://github.com/Linkurious/documentation/files/4205635/managing-users.zip)
[managing-groups.zip](https://github.com/Linkurious/documentation/files/4205670/managing-groups.zip)
[standard-access-rights.zip](https://github.com/Linkurious/documentation/files/4205680/standard-access-rights.zip)
[property-key-access-rights.zip](https://github.com/Linkurious/documentation/files/4205682/property-key-access-rights.zip)
[access-control-configuration-options.md.zip](https://github.com/Linkurious/documentation/files/4205683/access-control-configuration-options.md.zip)

**Comment by meaningfool** [comment]
Deleting my previous ticket (wrong doc ticket). Here is the md file for the search syntax
[search-syntax.md.zip](https://github.com/Linkurious/documentation/files/4205704/search-syntax.md.zip)

**Comment by meaningfool** [comment]
cc @davidrapin

**Comment by davidrapin** [comment]
@meaningfool please validate https://dev.linkurio.us/doc-next/user-manual/latest/search-syntax/

**Comment by fantandrea** [comment]
Regarding the part
> Search on numbers and dates only works with Elasticsearch under specific conditions. If you want to set this up, please get in touch.

In the admin section we already covered the case with the instructions on [how to activate the feature](https://dev.linkurio.us/doc-next/admin-manual/latest/es-config/#configuring-elasticsearch-v2x).
Maybe this should be the entry point before contacting the support.

**Comment by meaningfool** [comment]
@fantandrea my understanding is that configuration may not be enough, we also need ES to recognize the property as a number. If this does not happen then the client has to manually input a mapping in ES config. So my thinking here is, let them contact us so that:
- We can learn about who needs that and to do what
- We help them on a case-by-case basis
- Once we have a few examples that will help us write some better documentation and help us design a better search experience

@davidrapin @francescoinfante WDYT?

**Comment by meaningfool** [comment]
@davidrapin doc is ok for me

**Comment by thibaultlink** [comment]
Good for me too. Closing the issue.

**Comment by thibaultlink** [comment]
Reopening issue : 
@meaningfool numerical operators are "or equal". In the doc you said "Higher than". It should be "Higher or equal" and "Lower or equal".
Also, should we mention that the range is inclusive ?

**Comment by thibaultlink** [comment]
Added "or equal" after discussing it with @meaningfool . Closing.
