### ISSUE TITLE
Document all supported versions of external software

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#133]
Today we have some known compatibly issue with external software. This limitation are not documented:
- [x] Neo4j v4
- [x] MySQL v8
- [x] ElasticSearch v7

**Comment by fantandrea** [comment]
@davidrapin should it be fixed in 2.8.3?

**Comment by francescoinfante** [comment]
Neo4j v4 and ES 7 are documented 
first line here:
https://doc.linkurio.us/admin-manual/latest/configure-neo4j/

and almost first line here:
https://doc.linkurio.us/admin-manual/latest/es-config/

**Comment by davidrapin** [comment]
@fantandrea 2.8.3 is fine for me

**Comment by fantandrea** [comment]
@francescoinfante thanks for the notes, neo4j v4 was added in the latest doc. When we started the discussion it wasn't still available.

For the db version I think we can add a note [here](https://doc.linkurio.us/admin-manual/latest/user-data-store/) after the list.

What is the exact version constraint for both MySQL and MariaDB?

Are there other missing compatibility issues?

**Comment by francescoinfante** [comment]
@fantandrea I'm not aware of version compatibility for the SQL databases. it has to be tested.

For now this is what we are aware of: 
https://github.com/sequelize/sequelize/issues/9432
