### ISSUE TITLE
Custom actions

### ISSUE THREAD

**Issue by meaningfool** [Linkurious/documentation#135]
Kickstart ticket #30 https://github.com/Linkurious/kickstart/issues/30

Here is the .md and assets
[custom-actions.zip](https://github.com/Linkurious/documentation/files/4205598/custom-actions.zip)

**Comment by meaningfool** [comment]
@thibaultlink @davidrapin

**Comment by davidrapin** [comment]
note to self: integrated

**Comment by davidrapin** [comment]
@meaningfool please validate
https://dev.linkurio.us/doc-next/user-manual/latest/custom-actions/

**Comment by meaningfool** [comment]
@davidrapin I'm ok with most of the changes you made. However some information about incompatibilities between variables has been lost.

You mention only this
![image](https://user-images.githubusercontent.com/2862331/75449853-085feb80-596e-11ea-9128-837b9ba7961c.png)

But actually one cannot combine {{node}} with {{nodese}} or {{edgeset}}. Also if there are some constraints on a node category, then this constraint should apply to all instances of the variable: you cannot have {{node:COMPANY}} combined with {{node}}.

WDYT?

**Comment by davidrapin** [comment]
@meaningfool 
- regarding node/nodeset/edge/edgeset incompatibility, I decided to remove it since i thought that since it did not make sense from a semantic point of view, no one would try to do it, and if someone did, an error message would tell them about it. Let me know if you want to add it back.
- constraints: got it, let's add a phrase about the fact that `{{node:X}}` can only be mixed with other `{{node:X}}`, ok for you?

**Comment by davidrapin** [comment]
ping @meaningfool we need an answer ASAP

**Comment by thibaultlink** [comment]
@davidrapin we just validated both points from your last comment with  @meaningfool .  I propose replacing :
>"Several variables can be used in the same template (e.g. `https://google.com/search?q={{node.city}}+{{node.country}})`, the only constraint is that "node" and "edge" variables cannot be mixed."

With 
>"Several variables can be used in the same template (e.g. `https://google.com/search?q={{node.city}}+{{node.country}})`, with the constraint that "node" and "edge" variables cannot be mixed"

And adding : 
>"Two or more property variables can be used in a single custom action, as long as they all target the same node category or edge type (see 4th example)"

**Comment by davidrapin** [comment]
pushed, ready for validation

**Comment by thibaultlink** [comment]
Validated. Closing.
