### ISSUE TITLE
Property-key access rights

### ISSUE THREAD

**Issue by meaningfool** [Linkurious/documentation#136]
Kickstart ticket: https://github.com/Linkurious/kickstart/issues/93

I had to rework the whole doc structure. 

Here are the instructions regarding the doc structure:

Authentication (not clickable or empty index.md) (NEW)
	Authentication in Linkurious Enterprise (authentication-in-linkurious-enterprise)(NEW)
	LDAP / Active Directory
	SSO with Azure AD
	SSO with Google
	SSO with OpenID Connect
	SSO with SAML2 / ADFS

Access control (not clickable or access/index.md empty)
	REMOVE enable-auth.md
	REMOVE users.md
	Managing users (managing-users)(NEW)
	Managing groups (managing-groups)(NEW)
	Standard access rights (standard-access-rights)(NEW)
	Property-key access rights (property-key-access rights)(NEW)
	Access control configuration options (access-control-configuration-options) (NEW)

Guest mode (not clickable or empty) (NEW)
	Guest mode (guest-mode) (CHANGED DIRECTORY)

And here are the zip for each new page:
[authentication-in-linkurious-enterprise.zip](https://github.com/Linkurious/documentation/files/4205627/authentication-in-linkurious-enterprise.zip)
[managing-users.zip](https://github.com/Linkurious/documentation/files/4205635/managing-users.zip)
[managing-groups.zip](https://github.com/Linkurious/documentation/files/4205670/managing-groups.zip)
[standard-access-rights.zip](https://github.com/Linkurious/documentation/files/4205680/standard-access-rights.zip)
[property-key-access-rights.zip](https://github.com/Linkurious/documentation/files/4205682/property-key-access-rights.zip)
[access-control-configuration-options.md.zip](https://github.com/Linkurious/documentation/files/4205683/access-control-configuration-options.md.zip)

**Comment by meaningfool** [comment]
@davidrapin @thibaultlink

**Comment by davidrapin** [comment]
@meaningfool please validate 
https://dev.linkurio.us/doc-next/admin-manual/latest/access-control/

**Comment by meaningfool** [comment]
ok for me

**Comment by thibaultlink** [comment]
Also good for me. Closing.
