### ISSUE TITLE
Remove 38 mentions of Stardog (and DataStax and Allegrograph)

### ISSUE THREAD

**Issue by jvilledieu** [Linkurious/documentation#137]
Apparently there are 38 mentions of Stardog in the current version of the documentation: https://doc.linkurio.us/admin-manual/latest/page.html

Maybe we can remove those?

**Comment by fantandrea** [comment]
@jvilledieu the link you posted is for v2.7 where we still support it.

We dropped the support on v2.8, please check [https://doc.linkurio.us/admin-manual/2.8.2/page.html](https://doc.linkurio.us/admin-manual/2.8.2/page.html). If you are ok with this, you can close the issue (no actions to do).

**Comment by jvilledieu** [comment]
Thanks, perfect.
