### ISSUE TITLE
Missing "," in SQLite configuration

### ISSUE THREAD

**Issue by andre91a** [Linkurious/documentation#143]
Reference link: https://doc.linkurio.us/admin-manual/2.8.2/user-data-store/
In the section "Configure with SQLite" a "," is missing:

```
"db": {
    "name": "linkurious",
    "options": {
      "dialect": "sqlite" //MISSING , HERE
      "storage": "server/database.sqlite"
    }
}
```

Correct version:
```
"db": {
    "name": "linkurious",
    "options": {
      "dialect": "sqlite",
      "storage": "server/database.sqlite"
    }
}
```

**Comment by francescoinfante** [comment]
@fantandrea for issues like this I suggest you to create directly a commit to preprod or if you prefer a PR to it.

**Comment by fantandrea** [comment]
it's just for traceability since I'm already working on changes and will be part of my current commits
