### ISSUE TITLE
Company name mentioned instead of product name

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#146]
In many sections of the documentation, the company name `Linkurious` is mentioned instead of the product name `Linkurious Enterprise`.

Rename the occurrences with the appropriate `{{lke}}` tag.

**Comment by fantandrea** [comment]
@davidrapin this is a general comment raised by Maryline. I can invest some time in replacing all occurrences in my current branch of v2.8.3.

Not sure if something should be fixed in 2.9 as well and if we are able to maintain later on.


WDYT?

**Comment by davidrapin** [comment]
This can be solved in 5mn using regular expressions search+replace in WebStorm, I can help with that if you need.
Target versions would be 2.8.3, we are shipping 2.9 tomorrow (we're a bit short on time).

**Comment by fantandrea** [comment]
I can do it quite quickly as well on VS Code, however a bit of cross check is needed since many occurrences shouldn't be changes (checking for the capital L should already be 99.9999% accurate).

The question is if it make sense or we are just going to break the rule with the next doc update

**Comment by davidrapin** [comment]
let''s fix this :)

**Comment by fantandrea** [comment]
@davidrapin only remaining instances are related to copy/paste of the app.

E.g. `Start Linkurious` & `Stop Linkurious` from the menu script
`Linkurious ready to go :)` from the status API

do you want a fix in the code to change them?

**Comment by davidrapin** [comment]
Well done!
@fantandrea I think we don't need to go that far :D

**Comment by fantandrea** [comment]
@marilyne-linkurious can you validate and close?

**Comment by fantandrea** [comment]
Validated
