### ISSUE TITLE
Clarify the need to configure the schema to use the timeline

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#154]
According to https://secure.helpscout.net/conversation/1143223128/10235?folderId=3047731

Make more explicit the fact that the configuration should be done in the schema. Good spot first line of https://doc.linkurio.us/user-manual/2.8.3/timeline/

**Comment by fantandrea** [comment]
@tbolke Do you think may be useful to add some information also in the UI or do you want to keep it just in the documentation?

If you are just approaching to LKE and maybe you saw that you can use that button, you don't know what to do when it is gray.

**Comment by thibaultlink** [comment]
@tbolke @fantandrea moving this issue to 2.8.5. What is needed to close this issue ? After reading your comments it's not clear to me.

**Comment by thibaultlink** [comment]
@fantandrea We'd like to release today, that's why I moved the issue (to avoid being blocked because of a documentation issue).

**Comment by tbolke** [comment]
@davidrapin @fantandrea @marine-roy-link 
This ticket has already been fixed (https://github.com/Linkurious/documentation/commit/7d7ecb9bb0c5673bc13e59871b58aa9d3c829582) 
Can you pass it to validated? 
Thanks

**Comment by maxime-allex** [comment]
Good for me.

![Capture d’écran 2020-05-19 à 14.49.26.png](https://images.zenhubusercontent.com/5cc165004e45b82b5417531d/04d8e507-83f1-44c3-9ecc-8666a84b941f)
