### ISSUE TITLE
document supported RedHat server

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#158]
In this email:
https://secure.helpscout.net/conversation/1146189841/10246/
we discussed to a partner the supported RedHat versions.

We should add them to the doc.

**Comment by davidrapin** [comment]
We add in the doc the fact that we support RedHat 7.5+

**Comment by maxime-allex** [comment]
Good for me.

![Capture d’écran 2020-05-19 à 14.40.38.png](https://images.zenhubusercontent.com/5cc165004e45b82b5417531d/a505a3bb-4a88-4586-82e1-bc4922aec27a)
