### ISSUE TITLE
[admin manual] Explain how to prevent the access of users in AzureAD (and others identity providers?)

### ISSUE THREAD

**Issue by francescoinfante** [Linkurious/documentation#16]
From an answer to a client:

[...]
It’s not necessary to import all the Azure AD users into Linkurious. Indeed, it’s possible to restrict the access to an application (like Linkurious) associated with Azure following this tutorial:
https://docs.microsoft.com/en-us/azure/active-directory/active-directory-accessmanagement-group-saasapps
From within Azure itself you will be capable to assign which users and groups can log in into Linkurious.

The group mapping feature within Linkurious allows you to map groups of users from Azure to Linkurious, but every user not belonging to any of these groups will be mapped in the default group when logged into  Linkurious. To prevent this, you have to restrict their access within Azure as explained in the previous tutorial.
[...]

Explain this in the doc

**Comment by davidrapin** [comment]
partially false, you can set `access.externalUserDefaultGroupId` to external users with no group mapping in a group that have access to nothing.

**Comment by francescoinfante** [comment]
access to nothing !== prevent access, but yes. Also can we prevent access to every node? also node with no categories?

**Comment by davidrapin** [comment]
Good point, we could make a special right to edit nodes with no category.
Also, since we are redesigning access-rights, new types of groups and rights can be created.
