### ISSUE TITLE
Wrong Neo4j 4 support information

### ISSUE THREAD

**Issue by andre91a** [Linkurious/documentation#169]
In the Neo4j configuration page is still declared that there is no support for Neo4j 4 (https://doc.linkurio.us/admin-manual/2.9.1/configure-neo4j/)

Since there is a "minimum" support for version 4, In my opinion, it could be helpful to enlist in the page all the actually supported features.

<img width="975" alt="Schermata 2020-06-16 alle 10 14 04" src="https://user-images.githubusercontent.com/60261353/84749360-27849680-afba-11ea-9685-8892070f4dcd.png">

**Comment by davidrapin** [comment]
Thank you! 
@andre91a I proposed a fix for this
