### ISSUE TITLE
Add instructions for license.key in Docker

### ISSUE THREAD

**Issue by andre91a** [Linkurious/documentation#174]
Many docker users are dealing with the "expired license" message and in our docuementation there are no informations on how to manage the license

It's necessary to add these informations:
- how to retrieve the _license.key_
- how to import it in Linkurious Enterprise

**Comment by andre91a** [comment]
@davidrapin you proposed to add these informations here: https://doc.linkurio.us/admin-manual/2.9.1/install/ and it's ok for me. The only doubt is that, at this point of the documentation, the user still need to create the volumes for lke and the destination folder.

WDYT?

**Comment by davidrapin** [comment]
@andre91a Oh very good point, so what you are saying is that the details about the license should rather be in https://doc.linkurio.us/admin-manual/2.9.1/start/#docker-linux? That makes sense.

**Comment by andre91a** [comment]
@davidrapin Yes, a possible approach is to add the informations right after the creation of the volumes:
1. create the data folder with the same name of the volume
2. put license.key here

Another approach would be to add the informations after _run_ command. In this case they don't need to manually create the folder bu, on the other hand, they need to restart lke.

However I think the first approach is better

**Comment by davidrapin** [comment]
@andre91a I agree that the first approach seems simpler
