### ISSUE TITLE
[admin manual] document setting up a reverse proxy (nginx or apache)

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#18]
apache:
```
# see https://httpd.apache.org/docs/2.4/vhosts/examples.html#proxy
<VirtualHost *:80>
  ProxyPreserveHost On
  ProxyPass "/" "http://localhost:3000/"
  ProxyPassReverse "/" "http://localhost:3000/"
  ServerName domain.example.com
</VirtualHost>
```

**Comment by fantandrea** [comment]
Is the current description in the FAQ on [how to create a fault tolerance env](https://dev.linkurio.us/doc-next/admin-manual/latest/faq/#how-can-fault-tolerance-be-achieved) with nginx enough for this issue?

**Comment by davidrapin** [comment]
no one asked for apache again, so we can assume nginx is enough :)

**Comment by fantandrea** [comment]
Ok, then I'm closing it.
