### ISSUE TITLE
[admin manual] improve "install java" part

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#19]
- ubuntu: `sudo apt install default-jdk`
- gentoo `sudo emerge --ask virtual/jre`  
- centos: `sudo yum install java-1.7.0-openjdk`

 etc.

**Comment by davidrapin** [comment]
removing the milestone since this does not seems to be a priority

**Comment by fantandrea** [comment]
@davidrapin is this still of interest? If yes, is [this page](https://doc.linkurio.us/admin-manual/latest/requirements/#java) ok?

**Comment by davidrapin** [comment]
nobody seems to have issues with that, we can close
