### ISSUE TITLE
[admin manual] Update for v1.8.0

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#20]
- [x] DSE auth / ssl (clear about wss)
- [x] new process manager
- [x] `styles`  -> `defaultStyles` (config) #15 
- [x] self-signed CA
- [x] MSSQL 
- [ ] LDAP without admin account
- [ ] allSources -> advanced (config)

**Comment by davidrapin** [comment]
done

**Comment by francescoinfante** [comment]
- [ ] modify ldap

**Comment by francescoinfante** [comment]
updated LDAP doc

**Comment by francescoinfante** [comment]
LDAP: https://github.com/Linkurious/documentation/commit/f5556ad48eb3ea029ee1e40f2aeddc974e35786f

allsources -> advanced: https://github.com/Linkurious/documentation/commit/cc193b4672e1818374db012e3a53e47eeece6d77
