### ISSUE TITLE
Add Previous/Next page buttons at the end of site pages

### ISSUE THREAD

**Issue by sheymann** [Linkurious/documentation#3]
The user doc is a tutorial. User should be able to go to previous or next page simply.

**Comment by davidrapin** [comment]
Will do.

**Comment by davidrapin** [comment]
Done.

Use `{{entry.previous}}` and `{{entry.next}}` in markdown or html templates.

The text of the links can be configured in the JSON file with keys `"previousLink"` and `"nextLink"` . Defaults are "Previous" and "Next".

**Comment by sheymann** [comment]
Error:

>  * Generating HTML content from Markdown templates...
Variable reference "entry.previous" could not be resolved in "C:\Users\Seb\Documents\GitHub\documentation\content\user\content\main.md".

**Comment by davidrapin** [comment]
pull and check your version fo dokapi, package.json in documentation should use dokapi@1.0.15

**Comment by sheymann** [comment]
It works.
