### ISSUE TITLE
Add navigation header

### ISSUE THREAD

**Issue by sheymann** [Linkurious/documentation#4]
@davidrapin what menu items do we want?

**Comment by davidrapin** [comment]
for main menu:
- [ ] link to main linkurious website
- [ ] title of current doc
- [ ] link to all docs (page with links to `user doc`, `admin doc`, `ogma doc` and `server sdk doc`)
- [ ] maybe a menu to jump directly to one of our other docs

**Comment by sheymann** [comment]
@davidrapin need review on user doc site https://github.com/Linkurious/documentation/commit/36bb56827a52810a70f868b399b069e6f2e58edc

**Comment by davidrapin** [comment]
my feedback:
- css is great, very readable
- missing a hover effect for prev/next buttons
- menu to access other docs should be on the right of the navigation, not mixed with the site title. I would like a "select" menu with:
  - "see other versions" -> page with list of available versions of this doc
  - "admin doc"
  - "server sdk"
  -  "client sdk/ogma"

**Comment by davidrapin** [comment]
also, a link to linkurio.us wouldn't hurt

**Comment by sheymann** [comment]
@davidrapin done, need review
