### ISSUE TITLE
[Homepage and Server SDK] Change wording

### ISSUE THREAD

**Issue by elisedeux** [Linkurious/documentation#43]
Change the wording on the documentation [homepage](https://doc.linkurio.us/):

- In the user manual tile, add "Enterprise" after "Learn how to use Linkurious."
- In the administration manual tile, add "Enterprise" after "Learn how to setup and configure Linkurious."
- In the SDK doc tile, replace "Server SDK documentation" by "REST API documentation"

In the Server SDK doc, replace "Server SDK of Linkurious" by "Rest API of Linkurious" in the top left corner of the navigation bar.

**Comment by davidrapin** [comment]
Also fixed in:
- Ogma: https://github.com/Linkurious/ogma/commit/c96e634b9285a4db01183010637b29a82fa64908
- APIDoc template: https://github.com/Linkurious/apidoc/commit/ae99960bab24798da820374555accb154782e360

**Comment by francescoinfante** [comment]
Merged to preprod. Available for review here: https://dev.linkurio.us/doc
