### ISSUE TITLE
Add workspace shortcuts in doc

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/documentation#47]
In 2.6, the shortcuts modal disappear. The available shortcuts should be documented in a specific section.

<img width="1552" alt="capture d ecran 2018-09-27 a 11 34 55" src="https://user-images.githubusercontent.com/1384415/46137240-7ff58c80-c249-11e8-959e-6977bf7c2d97.png">
<img width="1552" alt="capture d ecran 2018-09-27 a 11 34 58" src="https://user-images.githubusercontent.com/1384415/46137241-808e2300-c249-11e8-80fd-e42f322ba578.png">

**Comment by fantandrea** [comment]
Section already available in [user doc](https://doc.linkurio.us/user-manual/latest/shortcuts/)
