### ISSUE TITLE
Describe available feature for each vendor

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#49]
For each graph database vendor page (e.g. https://doc.linkurio.us/admin-manual/latest/configure-neo4j/) add information about available features:
- graph search: yes
- visualization style customization: yes
- visualization filtering: yes
- graph edition: yes
- graph access-rights management: yes
- custom graph queries: yes/no
- custom graph query templates: yes/no
- graph alerts: yes/no

rfc @meaningfool

**Comment by davidrapin** [comment]
Alternatively, use a compiled table for easier comparison: e.g.
![screen shot 2018-10-03 at 20 16 25](https://user-images.githubusercontent.com/605880/46430476-535ddb00-c749-11e8-8c80-09b7d6e1282c.png)

**Comment by davidrapin** [comment]
@anabase we discussed this, let me know when you have time to put some time aside for this

**Comment by anabase** [comment]
@davidrapin What is graph edition?

**Comment by davidrapin** [comment]
graph edition = create and edit nodes / edges.

**Comment by anabase** [comment]
https://github.com/Linkurious/documentation/pull/59 awaiting review.

**Comment by francescoinfante** [comment]
Done:
https://doc.linkurio.us/admin-manual/latest/feature-map/
