### ISSUE TITLE
Guest mode query error

### ISSUE THREAD

**Issue by meaningfool** [Linkurious/documentation#50]
In the following page : https://doc.linkurio.us/admin-manual/latest/guest-mode/#populating-the-guest-mode-workspace
The URL for "pattern query" contains an error : there are "+" in the URL. The correct URL is : http://atlas.linkurio.us:3000/guest?populate=pattern&pattern_dialect=cypher&pattern_query=MATCH%20(n1)-%5Be%5D-(n2)%20WHERE%20ID(n1)%3D1211%20RETURN%20e

**Comment by francescoinfante** [comment]
solved
