### ISSUE TITLE
Improve admin documentation for Neo2ES partial indexation

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#56]
Add a documentation page about how to index only some of the nodes/edges in the DB by filtering by node label, edge type, property value, etc.

Some references here: https://github.com/graphaware/neo4j-framework/tree/master/common#inclusion-policies

**Comment by francescoinfante** [comment]
also tracked as a backend issue here:
https://github.com/Linkurious/linkurious-server/issues/1259

**Comment by anabase** [comment]
https://github.com/Linkurious/documentation/pull/59 awaiting review.

**Comment by francescoinfante** [comment]
Done:
https://doc.linkurio.us/admin-manual/latest/search-neo4j-to-elasticsearch/
