### ISSUE TITLE
Add a graph vendor / search solutions summary page

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/documentation#57]
For each vendor, describe all possible fulltext search solutions with pros and cons.
Dimensions:
1. easy onboarding (easy to configure)
2. fast indexation
3. index stays synced automatically (no need to reindex when the graph db changes)
4. responsive search at scale 
5. advanced search possible (e.g. search for number or date intervals)

### Neo4j
- embedded ES:
  - 1: plug and play
  - 2: no
  - 3: no
  - 4: no (becomes slow with more than 100M documents in regular hardware)
  - 5: yes (when enabled)
- dedicated ES:
  - 1: installation of ES necessary
  - 2: no
  - 3: no
  - 4: can scale horizontally by adding instances to ES cluster
  - 5: yes (when enabled)
- neo2es
  - 1: need to deploy ES, install plugin, set configuration options
  - 2: yes
  - 3: yes
  - 4: can scale horizontally by adding instances to ES cluster 
  - 5: no [possible future addition]
- neo4j search (pre 3.4)
  - 1: edition of the neo4j config file
  - 2: yes
  - 3: yes
  - 4: no
  - 5: no

### JanusGraph
TODO

### JanusGraph on Compose.com
TODO

### DSE Graph
DSE Search

### AllegroGraph
bultin search

### Stardog
bultin search

**Comment by davidrapin** [comment]
cc @francescoinfante @anabase

**Comment by fantandrea** [comment]
@davidrapin I guess this is covered by [this section](https://dev.linkurio.us/doc-next/admin-manual/latest/search-options/) right? Can we close?

**Comment by davidrapin** [comment]
yes! nice catch @fantandrea
