### ISSUE TITLE
Bad JSON in admin examples

### ISSUE THREAD

**Issue by sheymann** [Linkurious/documentation#6]
JSON given in example are not well-formed, e.g. "Geographic tiles" in the admin doc.

![image](https://cloud.githubusercontent.com/assets/177962/21996813/48b81b7a-dc2c-11e6-8815-16bf474147e4.png)

**Comment by davidrapin** [comment]
done

**Comment by sheymann** [comment]
Please scan all examples as there are other issues e.g.

![image](https://cloud.githubusercontent.com/assets/177962/22262452/34a4ec80-e271-11e6-8742-0b2d69b75156.png)

**Comment by davidrapin** [comment]
fixed for now
