### ISSUE TITLE
Change schema overview on 2.6 admin doc introduction page

### ISSUE THREAD

**Issue by elisedeux** [Linkurious/documentation#61]
Replace existing schema in [2.6 admin manual](https://doc.linkurio.us/admin-manual/2.6.0/) by the one attached that includes Cosmos DB as supported DB 
![arch_schema_3](https://user-images.githubusercontent.com/23723610/49091448-31239d80-f260-11e8-8f56-1bfb1e55bd0b.png)

**Comment by davidrapin** [comment]
Please udpate the SVG file here, we'll generate the PNG from that:
https://github.com/Linkurious/documentation/blob/preprod/content/admin/arch_schema.svg

David Rapin
CTO & co-founder
http://linkurio.us

**Comment by elisedeux** [comment]
Done
