### ISSUE TITLE
Document that we can only show graph query that returns Nodes and Edges (not tabular data)

### ISSUE THREAD

**Issue by maxime-allex** [Linkurious/documentation#69]
https://secure.helpscout.net/conversation/804428736/5584?folderId=490089

LKE for now only accept queries that will return nodes and/or edges. 

We should add this to the documentation, avoiding user to try to run other queries

**Comment by fantandrea** [comment]
@maxime-allex this issue is one year old. Today the doc already contains this.

> Note that the Cypher query has to contain a RETURN statement. Only nodes and edges returned are displayed. Returned values that are not a node or an edge (such as the `score` in the previous example) are not displayed.

Is it enough? Or was already the case last year and you would something more explicit?

**Comment by maxime-allex** [comment]
@fantandrea Fine for me. You can close. Thanks !
