### ISSUE TITLE
[rest api manual] Broken example in Widgets: Publish a widget

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#78]
Current code is raising the following error "TypeError: expandNodeRes.body.map is not a function [...]"

Working fix:
1. replace "expandNodeRes.body.map" with "expandNodeRes.body.nodes.map"
2. remove "nodeFields" and "edgeFields" attributes

**Comment by fantandrea** [comment]
Since the APIs on crunchbase server are done in https, also the generated URLs should be in https (on current configuration http requests are refused)

var widgetUrl = 'http://crunchbase.linkurio.us/widget/' + postWidgetRes.body;

Same issues on the three samples of the "Visualizations" section

**Comment by francescoinfante** [comment]
validated
