### ISSUE TITLE
Docker installation instruction

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#81]
The installation instruction in docker environment are broken. Using the -v option to externally mount the volumes won't work since the system is not able to write on them the first time

**Comment by francescoinfante** [comment]
They should be ok now @fantandrea 
can you check?
https://doc.linkurio.us/admin-manual/2.8.1/start/#docker-linux

**Comment by fantandrea** [comment]
It works and has been shipped with v2.7.7. (@francescoinfante should I also update the milestone?)

**Comment by francescoinfante** [comment]
updated the milestone
