### ISSUE TITLE
Update documentation screenshots for 2.8

### ISSUE THREAD

**Issue by thibaultlink** [Linkurious/documentation#82]
Screenshots need to be updated, specifically because we changed the way the admin menu is structured.

**Comment by thibaultlink** [comment]
Not done. Here's the list of pages where a screenshot needs to be updated.
It's always a screenshot of the "admin" dropdown menu from the dashboard.

https://dev.linkurio.us/doc/admin-manual/latest/configure/
https://dev.linkurio.us/doc/admin-manual/latest/configure-sources/
https://dev.linkurio.us/doc/admin-manual/latest/alternative-ids/
https://dev.linkurio.us/doc/admin-manual/latest/search/
https://dev.linkurio.us/doc/admin-manual/latest/enabling-auth/

**Comment by davidrapin** [comment]
@thibaultlink not a huge issue, moving forward

**Comment by fantandrea** [comment]
According to #110 also this page need to be reviewed:

https://dev.linkurio.us/doc/user-manual/latest/search-advanced/

**Comment by meaningfool** [comment]
What's the process for me to update screenshots @thibaultlink?

**Comment by thibaultlink** [comment]
@meaningfool I'm working on a process for writing and updating documentation but it won't be ready for a few weeks. In the meantime, what do you need to be able to update them ?

**Comment by fantandrea** [comment]
@thibaultlink this is the issue I was referring last time with the outdated images.

Another issue is with the images in the Guest Mode of the `Admin Section` (they are from some very old version of the system) [https://doc.linkurio.us/admin-manual/latest/guest-mode/](https://doc.linkurio.us/admin-manual/latest/guest-mode/).

Unless we need to refresh the images, I guess we can just reuse the same of the `User section` [https://doc.linkurio.us/user-manual/latest/guest/](https://doc.linkurio.us/user-manual/latest/guest/)

**Comment by meaningfool** [comment]
@thibaultlink at this point, I don't remember where the doc source code is stored and how/where I should upload an image file and change the links in the docs. 

I'll create .md files for new doc pages or largely edited pages. However I'm not sure how efficient it is for me to update a screenshot if there is no easy and straightforward to do it and check the result...

Let me know what seems workable

**Comment by thibaultlink** [comment]
I misunderstood the meaning of process here. I can totally write instructions on how to update the doc (incl. screenshots). I'll update here once the instructions are ready.

**Comment by meaningfool** [comment]
it'd be great to have a process, but nobody's is at fault: we did not take the time to actually make one... Here what I'm look for is an opinion / a clarification. I could very well do some screenshots and then pass it on to somebody else so that they are integrated in the doc. It probably would be faster to have 1 person do it all: make the screenshot and update the doc. WDYT? @davidrapin?

**Comment by davidrapin** [comment]
@meaningfool I'm 100% confident that writing instructions on how to update the user-manual and admin-doc would scale much better than having me be pinged/involved each time we need to change the doc :p

**Comment by davidrapin** [comment]
proposal: I will write instructions on how to update the doc this week and see if this helps.

**Comment by meaningfool** [comment]
I'm writing docs already. My question is specific to the case when we need to update screenshots.

**Comment by meaningfool** [comment]
Proposal: I can paste screenshots in this thread if that's convenient

**Comment by thibaultlink** [comment]
@meaningfool @davidrapin I made some short instructions on how to update screenshots : 
https://github.com/Linkurious/documentation/blob/preprod-next/Update_screenshots.md

**Comment by meaningfool** [comment]
I updated all images except for 
- authentication as it is refactored in 2.9 and already documented in another ticket
- guest mode since apparently I don't need to

Please note that image size may not be consistent with what it used to be. I can't go into it, and I need to move to other subjects. So I rely on you to fix this one last thing.

Thanks

**Comment by davidrapin** [comment]
@meaningfool which branch did you push the images in?

**Comment by meaningfool** [comment]
in develop-next as far as I remember

**Comment by thibaultlink** [comment]
this means `preprod-next` in this repo

**Comment by thibaultlink** [comment]
I replaced an extra screenshot. There's still some text to change in 5/6 pages in the doc. 
I dearly wish this was wordpress and I could edit pages in wysiwyg with a single click. Right now the extra steps make it quite a chore.
In any case I'm closing the issue.
