### ISSUE TITLE
Security block on windows installation

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#83]
Starting from Windows7 a new security feature consists in marking as blocked all executables and compressed archive downloaded from internet. In most cases this will prevent applications to work properly. It has been proved that this is impacting LKE v2.6.8

Update the installation process considering this extra step
From UI: https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/
From PowerShell: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-6

**Comment by thibaultlink** [comment]
This is not present in the documentation. @davidrapin it's not clear to me who's responsibility this is.

**Comment by davidrapin** [comment]
moving ahead, @fantandrea do you have a schedule to address this?

**Comment by fantandrea** [comment]
Not yet, I hope to be able to do it in the next couple of weeks (as well as Azure AD enhancement)

**Comment by fantandrea** [comment]
Validated.
