### ISSUE TITLE
CSS override feature is missing

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#84]
Describe the process to have custom CSS on the LKE.

Create override.css file in ./server/customFiles/assets/css

**Comment by thibaultlink** [comment]
@fantandrea what's the status of this issue ? Is this something that needs to be written in documentation ?

**Comment by davidrapin** [comment]
moving ahead to 2.8.2, @fantandrea do you have a schedule to address this?

**Comment by fantandrea** [comment]
Just before my holidays we discussed this point at the CSM weekly meeting. Seb said that we shouldn't document this part now since it would be one of the feature to be sell as extra package and we should get in touch with people using it right now.

**Comment by davidrapin** [comment]
ok, closing
