### ISSUE TITLE
Add instructions to export into external DB

### ISSUE THREAD

**Issue by fantandrea** [Linkurious/documentation#85]
Create and publish a script to sanitize the syntax based on this

Create import script:
```sh
sed 's/BEGIN TRANSACTION/START TRANSACTION/g ; s/AUTOINCREMENT/AUTO_INCREMENT/g ; s/ [+]00:00//g ; /^.*sqlite_sequence.*;$/d' export.sql > export-mariadb-import.sql
```

Create cleanup script:
```
sed -nE 's/^CREATE TABLE `([^`]*)`.*\;$/DROP TABLE IF EXISTS `\1`;/gp' export.sql > export-mariadb-cleardb.sql
```

**Comment by davidrapin** [comment]
@francescoinfante how did the script work for Safran?

**Comment by francescoinfante** [comment]
@davidrapin I'm sorry, but I'm not aware of this.
@fantandrea can you update me?

**Comment by davidrapin** [comment]
@fantandrea did this work with Safran? 
Can you attach the SQlite export file that got migrated with this script? We might have other issues to fix (e.g. booleans stored a smallinteger, etc.) 

We should compare the schema created by LKE directly on MariaDB by the schema created by the migrated script.

**Comment by fantandrea** [comment]
New version of the script attached to https://secure.helpscout.net/conversation/912785723/6880/ (dump-converter.sh)

It will truncate the content of all LKE tables and insert previous data. No changes to the database structure that has to be managed directly from LKE at the first startup before the script execution.

**Comment by thibaultlink** [comment]
@fantandrea does this need to be in the doc ? If so when do you think you could do it ?

**Comment by davidrapin** [comment]
@fantandrea what is the plan for this issue?

**Comment by fantandrea** [comment]
Last solution was to create two python scripts (I was able make a self contained package).
1. convert the mysql sql dump into a new one without the create table and making sure of the insert order
2. taking a sqlite file and a mysql sql connection compare the entire structure and data content (it is a migration validation script)

The steps worked for SAFRAN even if they required many steps. Would it worth to create a LKE plugin to do this migration (it should be quite simple to rewrite Python into TypeScript)? Or should I add those scripts + the instruction in the Doc?

**Comment by davidrapin** [comment]
Yes, we could put the script on github with instruction and mention it in
the doc.

**Comment by davidrapin** [comment]
@fantandrea removing frol 2.8.2 as this is not a blocking requirement for this release. Let me know what your strategy for improving the doc will be so that we can discuss how to go forward with this.

**Comment by fantandrea** [comment]
I started to work on the different doc issues. All of them are not related to a specific version so I would add them starting from the latest version. I can commit it on separate pull request so we can decide when to publish it.

**Comment by fantandrea** [comment]
The same script is going to be used again from Softlink, [here](https://secure.helpscout.net/conversation/1045547253/8933/#thread-2964249032) the thread with detailed steps to be copied/pasted when needed. I'll update the documentation soon.
