### ISSUE TITLE
API manual : "Search" section is present twice

### ISSUE THREAD

**Issue by thibaultlink** [Linkurious/documentation#97]
@francescoinfante not sure who's supposed to do this, please assign this to the correct person.

As title says, "Search" section is visible twice in the API manual on dev.linkurio.us/doc see screenshot : 
![image.png](https://images.zenhubusercontent.com/5cc1b8ac4e45b82b54175429/70991ab2-5aa9-4194-9f14-9b542e2bac19)

**Comment by francescoinfante** [comment]
done

**Comment by francescoinfante** [comment]
done b5a6b74

**Comment by thibaultlink** [comment]
Fixed.
